include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false

    # We want to use a limit of 120 characters
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    flutter_style_todos: false

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"

formatter:
  line-length: 120

