name: ui_kit
description: "Generic UI Kit for Flutter applications."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis:

flutter:
  assets:
    - assets/images/
